Feat: checkout app
luane-aquino/checkout pull request #1
Opened 2023-12-28 11:34 UTC by luane-aquino

2023-12-28 17:48 UTC, guilhermenasszup requested changes

2023-12-28 17:48 UTC, guilhermenasszup commented on src/components/atoms/Button/Button.test.tsx
Aqui eu criaria um teste para o cenário de desabilitado. Validar se o botão está desabilitado.

Verifica se o coverage deste arquivo está com uma porcentagem boa.

2023-12-28 17:48 UTC, guilhermenasszup commented on src/components/molecules/Product/ProductDescription/index.tsx
> +const ProductDescription = ({
Esse nome não é muito legal. 
Minhas sugestões: ProductData, ProductInfo ou apenas Product.

Por que? Porque não é apenas a descrição do produto, tem a imagem também.

2023-12-28 17:48 UTC, guilhermenasszup commented on src/components/molecules/Product/ProductDescription/index.tsx
> +    <li className="ProductDescription__list-item">
não acho legal colocar width e height assim. Colocaria em uma classe css

2023-12-28 17:48 UTC, guilhermenasszup commented on src/components/molecules/Product/ProductDescriptionWithPrice/styles.scss
> +  .desc {
evitar de abreviar palavras. Para muitos pode ser simples de entender que aqui estamos falando de descrição, mas nem sempre fica tão claro.

2023-12-28 17:48 UTC, guilhermenasszup commented on src/pages/ConfirmationSuccess/ConfirmationSuccess.test.tsx
> +        cardNumber: "1234567890123456",
Eu fiz uma refatoração nos testes aqui do projeto, justamente para tirar esse as any.

Você acha que consegue resolver de outra forma? Ou seja, sem usar as any,

2023-12-28 17:48 UTC, guilhermenasszup commented on src/pages/ConfirmationSuccess/index.tsx
> +        <PaymentPlan
Aqui uma provocação:
Invés de passar todos esses valores via prop para o componente, não seria mais fácil fazer a chamada do hook dentro do próprio componente do PaymentPlan?

`const { cart } = useCart() as CartContextType;`

2023-12-28 17:48 UTC, guilhermenasszup commented on src/pages/ErrorPage/index.tsx
Aqui a mensagem poderia ser em português.

2023-12-28 17:48 UTC, guilhermenasszup commented on src/utils/objectUtils.ts
Não vejo necessidade de uma função assim.

2024-01-09 12:27 UTC, luane-aquino commented on src/pages/ConfirmationSuccess/ConfirmationSuccess.test.tsx
> +        cardNumber: "1234567890123456",
Oi @guilhermenasszup , refatorei o teste e substitui o `any` pelo `jest.Mock`. Você fez de outra forma?

2024-01-11 02:54 UTC, luane-aquino commented on src/pages/ConfirmationSuccess/ConfirmationSuccess.test.tsx
> +        cardNumber: "1234567890123456",
subi as melhorias 🎉

2024-01-12 11:58 UTC, guilhermenasszup approved these changes

2024-01-15 12:12 UTC, merged